// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using invoicing.DB.DBContext;

#nullable disable

namespace invoicing.Migrations
{
    [DbContext(typeof(InvoicIngDbContext))]
    [Migration("20251227075018_AddOrderNumberExclusiveConstraint")]
    partial class AddOrderNumberExclusiveConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("invoicing.Models.Entity.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("公司編號");

                    b.Property<string>("CompanyFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("公司全名");

                    b.Property<string>("ContactPerson1")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("聯絡人一");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("送貨地址");

                    b.Property<string>("DeliveryZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("送貨地郵遞區號");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("傳真號碼");

                    b.Property<string>("InvoiceTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("發票抬頭");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone1")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("聯絡電話一");

                    b.Property<string>("Phone2")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("聯絡電話二");

                    b.Property<string>("RegisteredAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("登記地址");

                    b.Property<string>("TaxId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("統一編號");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("invoicing.Models.Entity.CustomerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Customer")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("客戶");

                    b.Property<string>("Customs")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasComment("關貿");

                    b.Property<string>("Date")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasComment("日期");

                    b.Property<string>("Deleted")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasComment("刪除");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NewOrderNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("新單子編號");

                    b.Property<string>("OrderName")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("單子");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("單子編號");

                    b.Property<string>("Remark")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("備註");

                    b.Property<string>("Time")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasComment("時間");

                    b.Property<string>("TotalAmount")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("總金額");

                    b.HasKey("Id");

                    b.HasIndex("NewOrderNumber")
                        .IsUnique()
                        .HasFilter("\"NewOrderNumber\" IS NOT NULL");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasFilter("\"OrderNumber\" IS NOT NULL");

                    b.ToTable("CustomerOrder", t =>
                        {
                            t.HasCheckConstraint("CK_OrderNumber_Exclusive", "(\"OrderNumber\" IS NOT NULL AND \"NewOrderNumber\" IS NULL) OR (\"OrderNumber\" IS NULL AND \"NewOrderNumber\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("invoicing.Models.Entity.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Amount")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("金額");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("單子編號");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("貨品編號");

                    b.Property<string>("ProductName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasComment("品名");

                    b.Property<string>("Quantity")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("數量");

                    b.Property<string>("Remark")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("備註");

                    b.Property<string>("Unit")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("基本單位");

                    b.Property<string>("UnitPrice")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("單價");

                    b.HasKey("Id");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("invoicing.Models.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CurrentCost")
                        .HasColumnType("numeric")
                        .HasComment("現行成本");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("PriceA")
                        .HasColumnType("numeric")
                        .HasComment("售價A");

                    b.Property<decimal?>("PriceB")
                        .HasColumnType("numeric")
                        .HasComment("售價B");

                    b.Property<decimal?>("PriceC")
                        .HasColumnType("numeric")
                        .HasComment("售價C");

                    b.Property<decimal?>("PriceD")
                        .HasColumnType("numeric")
                        .HasComment("售價D");

                    b.Property<decimal?>("PriceE")
                        .HasColumnType("numeric")
                        .HasComment("售價E");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("貨品編號");

                    b.Property<string>("ProductName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasComment("品名");

                    b.Property<decimal?>("StandardCost")
                        .HasColumnType("numeric")
                        .HasComment("標準成本");

                    b.Property<decimal?>("StandardPrice")
                        .HasColumnType("numeric")
                        .HasComment("標準售價");

                    b.Property<string>("Unit")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("基本單位");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("Product");
                });

            modelBuilder.Entity("invoicing.Models.Entity.SuggestedPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("StandardPrice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("標準售價");

                    b.Property<string>("SuggestedSalePrice")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("建議售價");

                    b.HasKey("Id");

                    b.ToTable("SuggestedPrice");
                });

            modelBuilder.Entity("invoicing.Models.Entity.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("帳單地址");

                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("公司編號");

                    b.Property<string>("CompanyFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("公司全名");

                    b.Property<string>("CompanyShortName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("公司簡稱");

                    b.Property<string>("ContactPerson1")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("聯絡人一");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("送貨地址");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("傳真號碼");

                    b.Property<string>("InvoiceTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("發票抬頭");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone1")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("聯絡電話一");

                    b.Property<string>("RegisteredAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("登記地址");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("備註");

                    b.Property<string>("ResponsiblePerson")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("負責人");

                    b.Property<string>("TaxId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("統一編號");

                    b.HasKey("Id");

                    b.ToTable("Supplier");
                });
#pragma warning restore 612, 618
        }
    }
}
